import manifesto from './marcas.json';

// Nome legível de cada logo (rótulo acessível). O resto vem do manifesto gerado por scripts/gerar-imagens.mjs.
const nomes: Record<string, string> = {
  'a-braba-da-99': 'A Braba da 99',
  'af-consultorias': 'AF Consultorias',
  'anna-rezende': 'Anna Rezende Psicologia',
  articulated: 'Articulated',
  'backhand-club': 'Backhand Club',
  'baterias-supply': 'Baterias Supply',
  'blitz-do-bafometro': 'Blitz do Bafômetro',
  'bm-assessoria-empresarial': 'BM Assessoria Empresarial',
  'brisa-do-pier': 'Brisa do Pier',
  bytro: 'Bytro',
  'car-burgers': 'Car Burgers',
  'chat-inteligente': 'Chat Inteligente',
  'conect-br-games': 'Conect BR Games',
  'congresso-nursing': 'Congresso Nursing',
  contai: 'Contai',
  cpet: 'CPET',
  'curso-tti-ead': 'Curso TTI EAD',
  desvvofit: 'DesvvoFit',
  dioliveira: 'DiOliveira',
  'doce-mana': 'Doce Maná',
  'dra-tamires-pereira-med-vet': 'Dra. Tamires Pereira, médica veterinária',
  'eclipse-viagens': 'Eclipse Viagens',
  'expert-option': 'ExpertOption',
  'fio-refrigeracao': 'Fio Refrigeração',
  flug: 'Flug',
  gnatus: 'Gnatus A.T.',
  'grupo-olimpia': 'Grupo Olímpia',
  'i9c-med': 'I9C Med',
  ibank: 'iBank',
  japedido: 'Japedido',
  lideranca: 'Liderança Empreendimentos',
  'lions-investment': 'Lions Investment',
  miw: 'MIW Wholesale Corp.',
  'mundo-burger': 'Mundo Burger',
  'neb-invest': 'NEB Invest',
  'new-york-donuts': 'New York Donuts',
  nuvemsign: 'NuvemSign',
  'olimpia-casa-grega': 'Olímpia Casa Grega',
  'prefeitura-de-sao-goncalo': 'Prefeitura de São Gonçalo',
  'rio-breeze': 'Rio Breeze',
  'seu-sirqueira': 'Seu Sirqueira',
  'teacher-gabriel-pinheiro': 'Teacher Gabriel Pinheiro',
  'tiberius-poker-club': 'Tiberius Poker Club',
  tolentinos: 'Tolentinos Restaurante',
  'tourex-broker': 'Tourex Broker',
  'vista-copacabana': 'Vista Copacabana',
  'ze-do-churrasco': 'Zé do Churrasco',
};

export type Marca = { slug: string; nome: string; largura: number; altura: number };

export const marcas: Marca[] = manifesto.map((m) => ({ ...m, nome: nomes[m.slug] ?? m.slug }));
